highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://indranilsinha.github.io
author: Indranil Sinha

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Indranil's blog
name: Indranil Sinha
email: mailneelhere@gmail.com
email_full: mailto:mailneelhere@gmail.com
website: indranilsinha.github.io
website_full: https://indranilsinha.github.io
github: trending
twitter: twitter
tel: 
tel_full: tel:
google_maps: ''
address:
  
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
